org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=scribble_book
mod_name=Scribble Book
mod_license=All Rights Reserved
mod_version=0.2.0+1.20.1
mod_group_id=org.skvipers
mod_authors=Mr. Skvipers
mod_description=A progressive block-study journal. Shift+RMB any block to record notes, unlock deeper knowledge, and browse your findings in a hand-crafted book UI.
